/**
 * Sentence Builder Api
 * An Api to that provides words of various word types. The types are Noun, Verb, Adjective, Adverb, Pronoun, Preposition, Conjunction, Determiner, Exclamation. Once the sentence has been built up, the user can persist the sentence in the backend.
 *
 * The version of the OpenAPI document: 1
 * Contact: jarryd.deane@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateSentenceWordDto } from './createSentenceWordDto';


export interface CreateSentenceDto { 
    /**
     * List of words in sentence
     */
    sentenceWords?: Array<CreateSentenceWordDto> | null;
}

